// Export all pages
export { default as HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as VideoPage } from './VideoPage'
export { default as ChannelPage } from './ChannelPage'
export { default as UploadPage } from './UploadPage'
export { default as EditVideoPage } from './EditVideoPage'
export { default as PlaylistPage } from './PlaylistPage'
export { default as PlaylistDetailPage } from './PlaylistDetailPage'
export { default as HistoryPage } from './HistoryPage'
export { default as LikedVideosPage } from './LikedVideosPage'
export { default as SubscriptionsPage } from './SubscriptionsPage'
export { default as DashboardPage } from './DashboardPage'
export { default as SearchPage } from './SearchPage'
export { default as SettingsPage } from './SettingsPage'
export { default as TweetsPage } from './TweetsPage'
export { default as NotFoundPage } from './NotFoundPage'
